openapi: 3.0.0
info:
  title: Fees and fines for bursar export schemas
  version: v1
servers:
  - url: https://stub.com/
paths:
  /stub:
    get:
      responses:
        "200":
          description: stub
components:
  schemas:
    userdataCollection:
      $ref: 'schemas/user/userCollection.json#/UserCollection'
    accountdataCollection:
      $ref: 'schemas/feesfines/accountdataCollection.json#/AccountdataCollection'
    feefineactionCollection:
      $ref: 'schemas/feesfines/feefineactionCollection.json#/FeefineactionCollection'
